/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package anawas.quadtree;

import java.awt.Rectangle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Rectangle rect = new Rectangle();
    }
}
