/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package anawas.quadtree;

import java.awt.Point;
import java.awt.Rectangle;
import java.util.Random;
import javax.swing.WindowConstants;

public class App {
    static final int WIDTH = 400;
    static final int HEIGHT = 400;

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Random random = new Random();
        Rectangle rect = new Rectangle(0,0,WIDTH,HEIGHT);
        QuadTree qtree = new QuadTree(rect, 4);
        for (int i = 0; i < 100; i++) {
            qtree.addPoint(new Point(random.nextInt(WIDTH), random.nextInt(HEIGHT)));
        }
        Canvas canvas = new Canvas();
        canvas.setSize(WIDTH, HEIGHT);
        canvas.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        canvas.drawQuadtree(qtree);
        canvas.setVisible(true);
    }
}
